<?php

declare(strict_types=1);

require_once __DIR__ . '/initial.theme.php';

/**
 * Implements hook_page_attachments_alter().
 */
function initial_page_attachments_alter(array &$attachments): void {
  $attachments['#attached']['library'][] = 'initial/global-styling';
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function initial_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if (!isset($variables['elements']['content']['#block_content'])) {
    return;
  }

  /** @var \Drupal\block_content\BlockContentInterface $content */
  $content = $variables['elements']['content']['#block_content'];
  $suggestions[] = 'block__block_content__' . $content->bundle();
}
