name: Deploy Drupal
on:

  # Runs on push to branch "main"
  push:
    branches: [ main ]

  # Runs when manually triggered in "Actions" tab
  workflow_dispatch:

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.ADMIN_IP }}
          user: ${{ secrets.ADMIN_USERNAME }}
          pass: ${{ secrets.ADMIN_PASS }}
          port: ${{ secrets.ADMIN_PORT }}
          script: |
            cd ~/DRUPAL-STARTER
            git fetch
            git pull
            ~/bin/composer install
            ~/bin/drush cr
            ~/bin/drush updb -y
            ~/bin/drush cim -y
            ~/bin/drush cr
